Tri ngo
Kenneth-W-Chen/mindfulness-app pull request #7
Opened 2024-10-11 15:36 UTC by Keido0208

2024-10-11 15:50 UTC, Kenneth-W-Chen requested changes
Remove the entire `backend` folder. Only push what's finished and what we're working on for this sprint
Remove `.dart_tool`

2024-10-11 15:50 UTC, Kenneth-W-Chen commented on .flutter-plugins
Remove this from git

2024-10-11 15:50 UTC, Kenneth-W-Chen commented on .flutter-plugins-dependencies
Remove this from git

2024-10-11 15:50 UTC, Kenneth-W-Chen commented on pubspec.lock
You deleted `sqflite`. Put it back

2024-10-14 15:21 UTC, Keido0208 commented on pubspec.lock
Put bacj sqflite

2024-10-14 15:39 UTC, closed without merging